{{- $bagetter := default (dict) .Values.bagetter -}}
{{- $apiKey := default .Values.apiKey $bagetter.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bagetter.fullname" . }}-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bagetter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey | b64enc | quote }}
