name: Release-Helm

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'
        required: true
        type: string
  
jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest

    env:
      CHART_DIR: deployment templates/chart
      CHART_REPO: bagetter/helm-chart-repo
      CHART_REPO_BRANCH: gh-pages
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the current repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Checkout the Helm chart repository
      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CHART_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.CHART_REPO_BRANCH }}

      # Update the Helm chart version
      - name: Update Helm Chart Version
        run: |
          sed -i "s/^version:.*/version: '${{ github.ref_name }}'/" ${{ env.CHART_DIR }}/bagetter/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: '${{ github.ref_name }}'/" ${{ env.CHART_DIR }}/bagetter/Chart.yaml

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # Package the Helm chart
      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package ${{ env.CHART_DIR }}/bagetter --destination .cr-release-packages

      # Install Chart Releaser
      - name: Install Chart Releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/latest/download/chart-releaser-linux-amd64.tar.gz | tar xz -C /usr/local/bin

      # Upload the packaged chart
      - name: Upload Helm Chart
        run: |
          cr upload --owner bagetter --git-repo helm-chart-repo --token ${{ secrets.GITHUB_TOKEN }} --package-path .cr-release-packages

      # Update the Helm chart index
      - name: Update Helm Chart Index
        run: |
          cr index --owner bagetter --git-repo helm-chart-repo --token ${{ secrets.GITHUB_TOKEN }} --charts-repo https://bagetter.github.io/helm-chart-repo --package-path .cr-release-packages
