name: Publish Helm Chart to helm-chart-repo

on:
  push:
    branches: [ "main" ]
    # Only run when chart content changes
    paths:
      - "charts/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-helm
  cancel-in-progress: false

env:
  CHART_NAME: bagetter
  CHART_DIR: charts/bagetter
  CHART_REPO_OWNER: bagetter
  CHART_REPO_NAME: helm-chart-repo
  PAGES_URL: https://helm.bagetter.com
  HELM_DOCS_URL: https://www.bagetter.com/docs/helm/overview
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BaGetter
        uses: actions/checkout@v4

      - name: Verify chart directory exists
        run: |
          if [ ! -f "${CHART_DIR}/Chart.yaml" ]; then
            echo "Chart.yaml not found at ${CHART_DIR}. Please update CHART_DIR or add the chart."
            exit 1
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Helm lint
        run: helm lint "${CHART_DIR}"

      - name: Build chart dependencies (if any)
        run: helm dependency build "${CHART_DIR}"

      - name: Get chart version
        id: chart_meta
        shell: bash
        run: |
          VERSION="$(grep -E '^version:' "${CHART_DIR}/Chart.yaml" | awk '{print $2}')"
          NAME="$(grep -E '^name:' "${CHART_DIR}/Chart.yaml" | awk '{print $2}')"
          if [ -z "$VERSION" ] || [ -z "$NAME" ]; then
            echo "Failed to parse name or version from Chart.yaml"
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Package chart
        run: |
          mkdir -p dist
          helm package "${CHART_DIR}" --destination dist
          ls -l dist

      - name: Clone helm-chart-repo gh-pages
        env:
          TOKEN: ${{ secrets.CHARTS_PUBLISH_TOKEN }}
        run: |
          set -euo pipefail
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          if git ls-remote --exit-code https://github.com/${CHART_REPO_OWNER}/${CHART_REPO_NAME}.git gh-pages >/dev/null 2>&1; then
            git clone --depth 1 --branch gh-pages "https://x-access-token:${TOKEN}@github.com/${CHART_REPO_OWNER}/${CHART_REPO_NAME}.git" repo
          else
            # Create gh-pages if missing
            git clone --depth 1 "https://x-access-token:${TOKEN}@github.com/${CHART_REPO_OWNER}/${CHART_REPO_NAME}.git" repo
            cd repo
            git checkout --orphan gh-pages
            rm -rf .
            touch .nojekyll
            echo "" > index.yaml
            git add .nojekyll index.yaml
            git commit -m "Initialize gh-pages"
            git push -u origin gh-pages
            cd ..
          fi

      - name: Build chart documentation
        run: |
          set -euo pipefail
          DOCS_DIR="repo/docs"
          SRC_DOCS_DIR="${CHART_DIR}/docs"
          mkdir -p "${DOCS_DIR}"

          cp "${CHART_DIR}/README.md" "${DOCS_DIR}/README.md"
          cp "${CHART_DIR}/values.yaml" "${DOCS_DIR}/values.yaml"
          if [ -f "${CHART_DIR}/values.schema.json" ]; then
            cp "${CHART_DIR}/values.schema.json" "${DOCS_DIR}/values.schema.json"
          fi

          if [ -d "${SRC_DOCS_DIR}" ]; then
            rm -rf "${DOCS_DIR}/reference"
            mkdir -p "${DOCS_DIR}/reference"
            cp -R "${SRC_DOCS_DIR}/." "${DOCS_DIR}/reference/"
          fi

          cat <<EOF > "${DOCS_DIR}/index.html"
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>BaGetter Helm Chart Documentation</title>
            <style>
              body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 2.5rem auto; max-width: 780px; line-height: 1.6; padding: 0 1.5rem; color: #0f172a; }
              h1 { font-size: 2.1rem; margin-bottom: 0.5rem; }
              p { margin-bottom: 1rem; }
              ul { padding-left: 1.25rem; }
              li { margin-bottom: 0.5rem; }
              a.button { display: inline-block; margin-top: 1rem; padding: 0.65rem 1.25rem; border-radius: 0.5rem; background: #2563eb; color: #fff; text-decoration: none; font-weight: 600; }
            </style>
          </head>
          <body>
            <h1>BaGetter Helm Chart</h1>
            <p>The full, continuously updated documentation now lives on the BaGetter Docusaurus site. Use the links below for quick access to raw chart assets or jump straight to the hosted guides.</p>
            <a class="button" href="${HELM_DOCS_URL}">Open Hosted Documentation</a>
            <section>
              <h2>Local References</h2>
              <ul>
                <li><a href="README.md">Chart README (Markdown)</a></li>
                <li><a href="values.yaml">Default values.yaml</a></li>
                <li><a href="values.schema.json">JSON schema</a></li>
              </ul>
            </section>
          </body>
          </html>
          EOF

          cat <<EOF > repo/index.html
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>BaGetter Helm Chart</title>
            <style>
              body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 2rem auto; max-width: 820px; line-height: 1.6; padding: 0 1.5rem; }
              h1 { font-size: 2.4rem; margin-bottom: 0.35rem; }
              section { margin-top: 2rem; }
              a.button { display: inline-block; margin-top: 0.75rem; padding: 0.65rem 1.15rem; border-radius: 0.5rem; background: #2563eb; color: #fff; text-decoration: none; font-weight: 600; }
              a.button.secondary { background: #64748b; }
              ul { padding-left: 1.2rem; }
            </style>
          </head>
          <body>
            <header>
              <h1>BaGetter Helm Chart</h1>
              <p>Find the packaged chart, reference assets, and published guides for deploying BaGetter to Kubernetes.</p>
            </header>
            <section>
              <h2>Documentation</h2>
              <ul>
                <li><a href="${HELM_DOCS_URL}">Hosted Docusaurus documentation</a></li>
                <li><a href="docs/README.md">Chart README (Markdown)</a></li>
                <li><a href="docs/values.yaml">Default values.yaml</a></li>
                <li><a href="docs/values.schema.json">JSON schema</a></li>
              </ul>
              <a class="button" href="${HELM_DOCS_URL}">Open Hosted Docs</a>
            </section>
            <section>
              <h2>Helm Repository</h2>
              <p>Add the Helm repository with:</p>
              <pre><code>helm repo add bagetter ${PAGES_URL}</code></pre>
              <a class="button secondary" href="index.yaml">View index.yaml</a>
            </section>
          </body>
          </html>
          EOF

      - name: Copy package and update index
        run: |
          set -euo pipefail
          cd repo
          mkdir -p ./
          cp -v ../dist/${{ steps.chart_meta.outputs.name }}-${{ steps.chart_meta.outputs.version }}.tgz ./ || true

          echo "helm.bagetter.com" > CNAME

          # Ensure .nojekyll
          touch .nojekyll

          # Merge/Update index.yaml
          if [ -f index.yaml ] && [ -s index.yaml ]; then
            helm repo index . --url "${PAGES_URL}" --merge index.yaml
          else
            helm repo index . --url "${PAGES_URL}"
          fi

          # Avoid re-adding the same version if it already exists
          # (If the .tgz already existed, helm repo index --merge will keep one entry)

          git add .nojekyll CNAME index.yaml *.tgz docs index.html || true
          if ! git diff --cached --quiet; then
            git commit -m "Publish ${{ steps.chart_meta.outputs.name }}-${{ steps.chart_meta.outputs.version }}"
            git push origin gh-pages
          else
            echo "No changes to commit (version may already be published)."
          fi
      - name: Summary
        run: |
          echo "Published chart:"
          echo "  Name:     ${{ steps.chart_meta.outputs.name }}"
          echo "  Version:  ${{ steps.chart_meta.outputs.version }}"
          echo "Repository URL: ${PAGES_URL}"

